image: python:3.7

stages:
  - test
  - integration-test

variables:
  AWS_DEFAULT_REGION: us-east-1

test:
  stage: test
  before_script:
    # Setup requirements
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install tox
  script:
    - tox

integration-test:
  stage: integration-test
  before_script:
    # Setup requirements
    - apt-get update -y && apt-get install -y awscli bats
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    # Setup skyscraper
    - pip install -r requirements.txt
    - pip install -U grpcio  # trouble with grpcio version
    - pip install -e .[aws,mqtt,redis]
    # Setup integration test environment
    - cp integration-tests/dotenv .env
    - echo 'AWS_ACCESS_KEY='$SKYSCRAPER_TESTING_ACCESS_KEY_ID >> .env
    - echo 'AWS_SECRET_ACCESS_KEY='$SKYSCRAPER_TESTING_SECRET_ACCESS_KEY >> .env
    - cat .env
    - mkdir $HOME/.aws
    - echo -e "[default]\naws_access_key_id = $SKYSCRAPER_TESTING_ACCESS_KEY_ID\naws_secret_access_key = $SKYSCRAPER_TESTING_SECRET_ACCESS_KEY\n" > $HOME/.aws/credentials
  script:
    - bats integration-tests/
